from datetime import datetime

import markdown as md_pkg

from src.models import GenerationResult
from src.utils import format_cost, sanitize_anchor

_CSS = """
body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    max-width: 860px;
    margin: 40px auto;
    padding: 0 20px;
    line-height: 1.6;
    color: #1a1a1a;
}
code, pre {
    background: #f5f5f5;
    border-radius: 4px;
    font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;
}
code { padding: 2px 5px; font-size: 0.9em; }
pre { padding: 16px; overflow-x: auto; }
pre code { background: none; padding: 0; }
h1, h2, h3 { font-weight: 600; }
hr { border: none; border-top: 1px solid #e0e0e0; margin: 32px 0; }
blockquote { border-left: 4px solid #e0e0e0; margin: 0; padding-left: 16px; color: #555; }
table { border-collapse: collapse; width: 100%; }
th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
th { background: #f5f5f5; }
"""


def format_markdown(result: GenerationResult, overview: str) -> str:
    """Assemble a complete Markdown document from a GenerationResult and overview text."""
    lines: list[str] = []

    lines.append(f"# {result.api_title} — API Documentation")
    lines.append(f"> Version {result.api_version}")
    lines.append("> Generated by AI Doc Generator")
    lines.append("")

    lines.append("## Overview")
    lines.append(overview)
    lines.append("")

    lines.append("## Table of Contents")
    for doc in result.docs:
        anchor = sanitize_anchor(doc.endpoint_ref)
        lines.append(f"- [{doc.endpoint_ref}](#{anchor})")
    lines.append("")

    lines.append("## Endpoints")
    lines.append("")
    for doc in result.docs:
        lines.append(f"### {doc.endpoint_ref}")
        lines.append("")
        lines.append(doc.markdown)
        lines.append("")
        lines.append("---")
        lines.append("")

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines.append("## Generation Stats")
    lines.append(f"- Model: {result.model}")
    lines.append(f"- Total tokens: {result.total_tokens}")
    lines.append(f"- Estimated cost: {format_cost(result.total_cost_usd)}")
    lines.append(f"- Generated at: {timestamp}")

    return "\n".join(lines)


def format_html(result: GenerationResult, overview: str) -> str:
    """Render the documentation as a self-contained HTML page with embedded CSS."""
    markdown_text = format_markdown(result, overview)
    body_html = md_pkg.markdown(markdown_text, extensions=["fenced_code", "tables"])
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{result.api_title} — API Documentation</title>
<style>{_CSS}</style>
</head>
<body>
{body_html}
</body>
</html>"""
